### ISSUE TITLE
Issues with bed installation

### ISSUE THREAD

**Issue by ModMike** [christophmuellerorg/voron_0_kirigami_bed#7]
Before I describe my issue, let me state, for the record, that I understand this issue has NOTHING to do with you, I am just looking for advice on how to install the bed properly.

I am having a serious issue with binding. Once the bed is tightened the rails rails bind because they are forced out of plane by the bed mounts. I tried tweaking the mounting ears to be in plane, then I designed and printed a part to clamp and the ears, but it only helped a little. Even you tubers such as Vecto 3D had the same issue during his stream, you can see it in his [video](https://www.youtube.com/watch?v=X-Wu85DuZxQ&t=9142s) at the 30 minute mark. He ended up using some TPU spacers but still had binding.

The problem is that factory tolerances and material flexibility make it so that mounting ears are out of plane. The first one I got was beyond tweaking. The replacement I received was better but still binds.

How do you recommend I fix this issue? For now, I ordered 2mm O-Rings to  put between the bed and the rails. I am hoping I can I can toque the screws in different amounts to align the carriers their rails. I just hope to be able to tighten them enough to remove any movement caused by flex between the two.

Let me know your thoughts, my V0.1 has been sitting around for 3 months.

Thanks!

**Comment by christophmuellerorg** [comment]
This is not typical, but I have seen some really bad tolerances on steel beds on Aliexpress (looking at you, Funssor...) which would easily cause serious issues due to the bends being out of spec. Check whether the flaps are in one plane and parallel to each other and verify whether the distance between both ends is 20mm - if not contact your vendor, it's a quality control issue on their side.
